[package]
name = "photos"
version = "0.1.0"
authors = ["andreioprea"]

[dependencies]
exif = {git="https://github.com/kamadak/exif-rs"}
iron = "0.6.0"
glob = "0.2"
iron-cors = "0.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
